import re
import json
import pandas as pd
import configparser
import psycopg2

with open('data.json') as f_in:
    data = json.load(f_in)

df_data = []

for i in range(len(data)):
    if data[i]['Type']=='md5':
        if re.match("([a-fA-F\d]{32})", data[i]['Value']):
            df_data.append({'Type': data[i]['Type'], 'Value': data[i]['Value']} )

    if data[i]['Type']=='sha256':
        if re.match("([a-fA-F\d]{64})", data[i]['Value']):
            df_data.append({'Type': data[i]['Type'], 'Value': data[i]['Value']} )

    if data[i]['Type']=='domain':
        if re.match("^((?!-)[A-Za-z0-9-]{1,63}(?<!-)\\.)+[A-Za-z]{2,6}$", data[i]['Value']):
            df_data.append({'Type': data[i]['Type'], 'Value': data[i]['Value']} )

df = pd.DataFrame(df_data)
unique_values = df['Value'].unique()
count, unique_types = [], []
for i in range(len(unique_values)):
    count.append(df[df['Value']== unique_values[i]]['Value'].count())
    unique_types.append(df[df['Value']==unique_values[i]]['Type'].iloc[0])

df1 = pd.DataFrame()
df1['Type'] = unique_types
df1['Value'] = unique_values
df1['Count'] = count

config = configparser.ConfigParser()
config.read("config.ini")
path = str(config["CSV"]["csv_path"]).replace("\\", "/")
df1.to_csv(path_or_buf = path, index=False)

config = configparser.ConfigParser()
config.read("config.ini")
path = str(config["CSV"]["csv_path"]).replace("\\", "/")

conn = psycopg2.connect(database=config["PSQL"]['database'], user=config["PSQL"]['user'],
    password=config["PSQL"]['password'], host=config["PSQL"]['host'], port=config["PSQL"]['port'])
cur = conn.cursor()
cur.execute("CREATE TABLE table_name (id int generated by default as identity not null, Type varchar(50), Value varchar(256))")

for i in range (len(df1['Type'])):
    cur.execute("INSERT INTO table_name (id, Type, Value) VALUES (%s, %s, %s)", (i+1, df1.iloc[i][0], df1.iloc[i][1]))
conn.commit()
cur.close()
